const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType, LevelFormat
} = require('docx');
const fs = require('fs');

const b = { style: BorderStyle.SINGLE, size: 1, color: "AAAAAA" };
const borders = { top: b, bottom: b, left: b, right: b };

const h1 = t => new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: t, bold: true, color: "1F3864", size: 30 })] });
const h2 = t => new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: t, bold: true, color: "2E4A8A", size: 26 })] });
const h3 = t => new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text: t, bold: true, color: "1F5C8B", size: 23 })] });
const p = (t, opts={}) => new Paragraph({ spacing: { after: 100, before: 60 }, children: [new TextRun({ text: t, ...opts })] });
const bp = (label, text) => new Paragraph({ spacing: { after: 80, before: 60 }, children: [new TextRun({ text: label + ": ", bold: true }), new TextRun({ text })] });
const bul = t => new Paragraph({ numbering: { reference: "bullets", level: 0 }, spacing: { after: 60 }, children: [new TextRun({ text: t })] });
const bulB = (l, t) => new Paragraph({ numbering: { reference: "bullets", level: 0 }, spacing: { after: 60 }, children: [new TextRun({ text: l, bold: true }), new TextRun({ text: ": " + t })] });
const num = t => new Paragraph({ numbering: { reference: "numbers", level: 0 }, spacing: { after: 60 }, children: [new TextRun({ text: t })] });
const sp = () => new Paragraph({ children: [new TextRun("")], spacing: { after: 80 } });
const hr = () => new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "3366AA", space: 1 } }, spacing: { after: 120, before: 120 }, children: [] });

const qHead = (n, m, t) => new Paragraph({
  spacing: { after: 80, before: 160 },
  children: [
    new TextRun({ text: `Q${n}. `, bold: true, color: "C0392B", size: 24 }),
    new TextRun({ text: `[${m} Marks] `, bold: true, color: "7D3C98", size: 22 }),
    new TextRun({ text: t, bold: true, size: 22 })
  ]
});

const secBox = title => new Table({
  width: { size: 9360, type: WidthType.DXA }, columnWidths: [9360],
  rows: [new TableRow({ children: [new TableCell({
    borders, width: { size: 9360, type: WidthType.DXA },
    shading: { fill: "1F3864", type: ShadingType.CLEAR },
    margins: { top: 100, bottom: 100, left: 200, right: 200 },
    children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: title, bold: true, color: "FFFFFF", size: 28 })] })]
  })]})],
});

const tbl = (c1, c2, rows) => {
  const hRow = new TableRow({ children: [c1, c2].map(c => new TableCell({
    borders, width: { size: 4680, type: WidthType.DXA },
    shading: { fill: "2E4A8A", type: ShadingType.CLEAR },
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    children: [new Paragraph({ children: [new TextRun({ text: c, bold: true, color: "FFFFFF" })] })]
  })) });
  const dRows = rows.map((r, i) => new TableRow({ children: r.map(cell => new TableCell({
    borders, width: { size: 4680, type: WidthType.DXA },
    shading: { fill: i % 2 === 0 ? "F2F4F4" : "FFFFFF", type: ShadingType.CLEAR },
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    children: [new Paragraph({ children: [new TextRun({ text: cell })] })]
  })) }));
  return new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [4680, 4680], rows: [hRow, ...dRows] });
};

const tbl3 = (c1, c2, c3, rows) => {
  const w = 3120;
  const hRow = new TableRow({ children: [c1, c2, c3].map(c => new TableCell({
    borders, width: { size: w, type: WidthType.DXA },
    shading: { fill: "1F3864", type: ShadingType.CLEAR },
    margins: { top: 80, bottom: 80, left: 100, right: 100 },
    children: [new Paragraph({ children: [new TextRun({ text: c, bold: true, color: "FFFFFF", size: 18 })] })]
  })) });
  const dRows = rows.map((r, i) => new TableRow({ children: r.map(cell => new TableCell({
    borders, width: { size: w, type: WidthType.DXA },
    shading: { fill: i % 2 === 0 ? "EBF5FB" : "FFFFFF", type: ShadingType.CLEAR },
    margins: { top: 80, bottom: 80, left: 100, right: 100 },
    children: [new Paragraph({ children: [new TextRun({ text: cell, size: 18 })] })]
  })) }));
  return new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [w, w, w], rows: [hRow, ...dRows] });
};

const children = [
  // Title
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 400, after: 200 }, children: [new TextRun({ text: "CLOUD COMPUTING", bold: true, size: 48, color: "1F3864" })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 100 }, children: [new TextRun({ text: "UNIT – IV: Cloud Computing Challenges", bold: true, size: 36, color: "2E4A8A" })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 100 }, children: [new TextRun({ text: "B.Tech VI Semester | Ramachandra College of Engineering, Eluru", size: 24, color: "555555" })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 400 }, children: [new TextRun({ text: "Question Bank – Detailed Answers", italics: true, size: 24, color: "777777" })] }),
  hr(),

  // ===== SHORT ANSWER =====
  sp(), secBox("SECTION A – SHORT ANSWER QUESTIONS (2 Marks Each)"), sp(),

  // Q1
  qHead(1, 2, "Define the economics of cloud computing."),
  p("The economics of cloud computing refers to the financial model in which IT resources are delivered and consumed as a service, transforming capital expenditure (CAPEX) into operational expenditure (OPEX)."),
  p("Key aspects:"),
  bulB("Pay-as-you-go", "Enterprises pay only for what they use, eliminating idle resource costs."),
  bulB("Reduced Capital Costs", "No need to purchase expensive IT hardware or software licenses."),
  bulB("No Depreciation", "Cloud removes long-term depreciation costs on hardware/software assets."),
  bulB("Subscription-based Software", "Replaces costly one-time licenses with flexible monthly/annual subscriptions."),
  bulB("Lower Maintenance Costs", "Cloud providers handle upgrades, security, and backups, reducing in-house IT expenses."),
  p("Primary drivers: economies of scale and simplified software delivery and operations."),
  hr(),

  // Q2
  qHead(2, 2, "State the need for standards in cloud computing."),
  p("Standards in cloud computing are essential for ensuring interoperability, portability, and fair competition across cloud providers."),
  bulB("Prevent Vendor Lock-in", "Proprietary technologies trap customers with one provider. Standards allow seamless migration."),
  bulB("Interoperability", "Enables different cloud systems to work together without compatibility issues."),
  bulB("Portability", "Standards like Open Virtualization Format (OVF) allow VM images to be moved across providers."),
  bulB("Consistent APIs", "A common API framework lets applications work across multiple clouds without rewrites."),
  bulB("Security & Compliance", "Standardized frameworks (e.g., NIST, ISO 27001) ensure consistent security policies."),
  p("Key organizations: Cloud Computing Interoperability Forum (CCIF), Open Cloud Consortium, DMTF Cloud Standards Incubator, Open Cloud Manifesto."),
  hr(),

  // Q3
  qHead(3, 2, "Explain the concept of scalability in cloud systems."),
  p("Scalability is the capability of a cloud system to grow and handle increased workload without performance degradation."),
  p("Cloud middleware must support scalability across three dimensions:"),
  bulB("Performance Scalability", "Ability to handle higher workloads efficiently as demand increases."),
  bulB("Size Scalability", "Ability to seamlessly add more resources – compute, storage, networking."),
  bulB("Load Scalability", "Ability to balance workloads dynamically across distributed resources."),
  p("Unlike traditional in-house IT systems, cloud enables enterprises to expand beyond their own infrastructure limits. This access to virtually unlimited computing power eliminates the need for large capital investments in physical hardware."),
  hr(),

  // Q4
  qHead(4, 2, "What is fault tolerance and why is it important in clouds?"),
  p("Fault tolerance is the ability of a cloud system to continue operating correctly even in the event of hardware or software failures."),
  p("Why it is important:"),
  bulB("Scale of Failures", "In large-scale cloud environments with thousands of servers, hardware failures are not exceptional events – they are inevitable."),
  bulB("Continuous Availability", "Cloud services must be available 24/7. Downtime directly impacts business revenue and SLA compliance."),
  bulB("Resilience", "Fault-tolerant systems use redundancy, replication, and self-healing mechanisms to continue operations."),
  bulB("Disaster Recovery", "Automated failover and backup mechanisms reduce the impact of catastrophic failures."),
  p("The key challenge: building middleware that ensures resilience to failures while maintaining cost efficiency and competitive performance."),
  hr(),

  // Q5
  qHead(5, 2, "Explain the importance of energy efficiency in cloud data centers."),
  p("Energy efficiency in cloud data centers is critically important due to the massive and growing power consumption of modern data centers."),
  bulB("Environmental Impact", "A typical data center consumes as much energy as 25,000 households. Carbon emissions from data centers exceed those of entire countries like Argentina and the Netherlands."),
  bulB("Financial Impact", "Amazon estimates that 42% of its data center budget is energy-related (direct electricity + cooling). Energy costs double every 5 years."),
  bulB("Sustainability", "With rising energy costs and declining energy availability, the current model is unsustainable."),
  bulB("Green Cloud", "Energy-efficient resource management reduces power costs, carbon emissions, and maximizes revenue."),
  p("Techniques: VM consolidation (packing workloads onto fewer servers), dynamic VM migration, and Dynamic Voltage and Frequency Scaling (DVFS)."),
  hr(),

  // Q6
  qHead(6, 2, "What are federated clouds?"),
  p("Federated clouds (also called Cloud Federation or InterCloud) are mechanisms that allow different, independent cloud providers to interoperate, enabling market-oriented cloud computing such as resource trading, workload shifting, and service sharing."),
  p("Definition (Reuven Cohen, Enomaly Inc.): \"Cloud federation manages consistency and access controls when two or more independent, geographically distinct Clouds share authentication, files, computing resources, command and control, or access to storage resources.\""),
  p("Key features:"),
  bulB("Agreements & Proprietary Interfaces", "Based on agreements between independent cloud providers."),
  bulB("Financial Agreements", "Since Cloud services are pay-per-use, federation typically involves financial contracts between providers."),
  bulB("Market-Oriented", "Enables resource trading and workload shifting based on demand and cost."),
  hr(),

  // Q7
  qHead(7, 2, "Explain the cloud shared responsibility model."),
  p("The Cloud Shared Responsibility Model (SRM) is a security framework that clearly defines who – the Cloud Service Provider (CSP) or the Customer – is responsible for securing different aspects of the cloud environment."),
  bulB("CSP Responsibility", "Secures the cloud itself: physical infrastructure, hardware, virtualization, networking, and data center facilities."),
  bulB("Customer Responsibility", "Secures what they put in the cloud: applications, data, user identities, configurations, and access policies."),
  p("The division of responsibilities varies by service model:"),
  bulB("IaaS", "CSP secures infrastructure; customer manages OS, apps, data, IAM."),
  bulB("PaaS", "CSP manages infrastructure + platform; customer secures app code and data."),
  bulB("SaaS", "CSP manages almost everything; customer responsible only for data security and access control."),
  hr(),

  // Q8
  qHead(8, 2, "Define cloud computing security."),
  p("According to Gartner: \"Cloud security refers to the processes, mechanisms, and services used to control the security, compliance, and other usage risks of cloud computing.\""),
  p("Cloud computing security is a comprehensive set of strategies, technologies, and policies designed to safeguard cloud-hosted data centers, applications, and resources from cyberattacks and unauthorized access."),
  p("Typical cloud security solutions include:"),
  bul("Firewalls"), bul("Network Access Controls (NACs)"), bul("Virtual Private Networks (VPNs)"), bul("Identity & Access Management (IAM)"), bul("Web Application Firewalls (WAFs)"), bul("Encryption and data protection mechanisms"),
  p("Cloud security addresses the CIA triad: Confidentiality (preventing unauthorized access), Integrity (preventing unauthorized modification), and Availability (ensuring systems are accessible when needed)."),
  hr(),

  // Q9
  qHead(9, 2, "Define the concept of cloud interoperability."),
  p("Cloud interoperability is the ability of different cloud systems, platforms, and services from multiple vendors to work together seamlessly, allowing data, applications, and workloads to move across cloud environments without significant modification or migration costs."),
  p("Goals:"),
  bulB("Portability", "Move applications and data between clouds without compatibility issues."),
  bulB("Integration", "Connect services from different providers to build complex workflows."),
  bulB("Prevent Lock-in", "Allow enterprises to switch providers based on cost, performance, or compliance needs."),
  p("Initiatives: Open Virtualization Format (OVF) for VM portability; AWS-compatible APIs adopted by open-source IaaS providers; DMTF Cloud Standards Incubator for common APIs."),
  p("Challenge: APIs remain vendor-specific today; true universal interoperability standards are not yet fully established."),
  hr(),

  // Q10
  qHead(10, 2, "Explain security issues in different cloud deployment models."),
  h3("Private Cloud Security Issues:"),
  bulB("Physical Security", "Organizations may lack robust surveillance, fire protection, and restricted access compared to large CSPs."),
  bulB("Insider Threats", "Privileged administrators with access can intentionally or accidentally cause breaches."),
  bulB("Patch Management Gaps", "Delays in applying updates leave vulnerabilities exposed."),
  bulB("IAM Weaknesses", "Misconfigured access policies can enable unauthorized access."),
  h3("Public Cloud Security Issues:"),
  bulB("Multi-Tenancy Risks", "Shared infrastructure increases risk of cross-tenant attacks via hypervisor vulnerabilities."),
  bulB("Lack of Visibility", "Cloud resources outside local IT control create monitoring blind spots."),
  bulB("Misconfigurations", "Default settings and weak configurations are a major cause of breaches."),
  bulB("DDoS Attacks", "Public-facing services are prime targets for Distributed Denial of Service attacks."),
  h3("Hybrid Cloud Security Issues:"),
  bulB("Data Leakage in Transit", "Data moving between private and public environments is vulnerable to interception."),
  bulB("Compliance Challenges", "Data movement across regions complicates adherence to GDPR, HIPAA, PCI-DSS."),
  bulB("SLA Misalignment", "Different APIs and SLAs across providers complicate consistent service delivery."),
  bulB("Skills Gap", "Managing security across multiple cloud platforms requires expertise that is often lacking."),
  hr(),

  // ===== LONG ANSWER =====
  sp(), secBox("SECTION B – LONG ANSWER QUESTIONS"), sp(),

  // Q1.a
  qHead("1.a", 5, "Describe the fundamentals of computer security in relation to cloud computing."),
  h3("Definition (NIST):"),
  p("\"Prevention of damage to, protection of, and restoration of computers, electronic communications systems, electronic communications services, wire communication, and electronic communication, including information contained therein, to ensure its availability, integrity, authentication, confidentiality, and non-repudiation.\""),
  p("Computer security refers to a set of concepts, tools, and technologies designed to ensure the Confidentiality, Integrity, and Availability (CIA) of data and information. In cloud computing, securing data becomes more complex because data is stored remotely, accessed over the internet, and shared across multi-tenant environments."),
  h3("Four Categories of Computer Security:"),
  h3("1. Application Security:"),
  p("Protects applications and associated data from unauthorized access, misuse, or intrusion."),
  bulB("Subdomains", "Web application security, API security, Cloud-native application security."),
  bulB("Example", "The OWASP Top 10 highlights the most critical cloud-native security risks including insecure configs, injection flaws, and weak authentication."),
  bulB("Cloud Aspect", "Protects cloud-hosted apps via WAFs, vulnerability scanning, and secure coding practices."),
  h3("2. Network Security:"),
  p("Safeguards systems, data, and services from unauthorized access and cyberattacks during network communication."),
  bulB("Subdomains", "Physical security (hardware), Technical security (firewalls, IDS/IPS, VPNs), Administrative security (access policies)."),
  bulB("Common Threats", "Phishing, DoS/DDoS, Malware, Ransomware."),
  bulB("Cloud Aspect", "Protects traffic between cloud environments and on-premises infrastructure."),
  h3("3. Information Security:"),
  p("Protects information – physical or digital – from unauthorized access, disclosure, modification, destruction, or disruption."),
  p("Key Principles (CIA Triad + Extensions):"),
  bulB("Confidentiality", "Prevent unauthorized disclosure of data."),
  bulB("Integrity", "Prevent unauthorized modification of data."),
  bulB("Availability", "Ensure information is accessible when needed."),
  bulB("Nonrepudiation", "Ensure accountability of transactions."),
  bulB("Authenticity", "Verify trusted sources."),
  bulB("Accountability", "Track and control user access."),
  bulB("Cloud Aspect", "Secure application hosting and consumption of third-party cloud services."),
  h3("4. Endpoint Security:"),
  p("Secures end-user devices such as PCs, laptops, smartphones, and IoT devices from cyberattacks."),
  bulB("Techniques", "Antivirus tools, anti-malware, device monitoring, and endpoint protection policies."),
  bulB("Cloud Aspect", "Built into cloud service access policies, ensuring secure user-device interactions with cloud infrastructure."),
  h3("Cryptography as a Core Security Concept:"),
  p("Cryptography uses mathematical algorithms to encrypt data (Plaintext → Ciphertext) and decrypt it back. It ensures:"),
  bulB("Confidentiality", "Only authorized parties can read the data (e.g., HTTPS for web browsing)."),
  bulB("Integrity", "Data is not altered during transmission (hash functions, digital signatures)."),
  bulB("Nonrepudiation", "Sender cannot deny sending a message (digital signatures)."),
  bulB("Authentication", "Verifies identity of sender and receiver (MFA in online banking)."),
  hr(),

  // Q1.b
  qHead("1.b", 5, "Explain scalability and fault tolerance in cloud systems."),
  h3("Scalability in Cloud Systems:"),
  p("Scalability is the capability of a cloud system to grow and manage increased workloads without performance degradation."),
  p("Cloud middleware must be designed to scale across three dimensions:"),
  bulB("Performance Scalability", "Ability to handle higher computational workloads efficiently. Example: Adding more CPU cores to handle a spike in web traffic during a sale event."),
  bulB("Size Scalability", "Ability to seamlessly add more resources (compute, storage, network). Example: AWS Auto Scaling automatically adds EC2 instances based on demand."),
  bulB("Load Scalability", "Ability to distribute workloads evenly across distributed resources to prevent bottlenecks. Example: Load balancers distributing requests across multiple servers."),
  p("Types of Scaling:"),
  bulB("Vertical Scaling (Scale Up)", "Adding more power to an existing machine (more CPU, RAM). Limited by hardware capacity."),
  bulB("Horizontal Scaling (Scale Out)", "Adding more machines to the resource pool. Preferred in cloud environments for elasticity."),
  p("Benefit: Enterprises gain access to virtually unlimited computing power that would otherwise require massive capital investments and high maintenance costs."),
  h3("Fault Tolerance in Cloud Systems:"),
  p("Fault tolerance is the ability of a cloud system to continue operating properly even when components fail – hardware failures, software errors, or network outages."),
  p("Why it is critical:"),
  bulB("Scale of Deployments", "In cloud environments with thousands of servers, failures are not exceptional – they are routine events."),
  bulB("24/7 Availability Requirement", "Cloud SLAs typically guarantee 99.9% or 99.99% uptime. Downtime violates agreements and costs revenue."),
  p("Key Fault Tolerance Mechanisms:"),
  bulB("Redundancy", "Duplicate components (servers, storage, network links) so that if one fails, another takes over."),
  bulB("Replication", "Data is replicated across multiple geographic availability zones."),
  bulB("Self-Healing", "Middleware automatically detects failures and restarts or replaces failed components."),
  bulB("Disaster Recovery", "Automated backup and failover mechanisms restore services after catastrophic failures."),
  bulB("Load Balancing", "Distributes traffic across healthy servers, redirecting away from failed ones."),
  h3("Combined Challenge:"),
  p("The real challenge is building systems that are simultaneously: highly scalable (handle growing demand), fault-tolerant (survive failures), easy to manage, cost-efficient, and able to deliver competitive performance to meet customer SLAs."),
  hr(),

  // Q2
  qHead(2, 10, "Discuss the cloud shared responsibility model with an example."),
  h3("Definition:"),
  p("The Cloud Shared Responsibility Model (SRM) is a security framework that clearly defines which security tasks are the responsibility of the Cloud Service Provider (CSP) and which remain the responsibility of the Customer, across different cloud service models."),
  bulB("CSP Responsibility", "Secures 'the cloud itself' – physical data centers, hardware, networking, virtualization layer, and global infrastructure."),
  bulB("Customer Responsibility", "Secures 'what they put in the cloud' – applications, data, user identities, access configurations, and compliance."),
  h3("Shared Responsibility Across Service Models:"),
  sp(), tbl3("Element", "IaaS", "PaaS / SaaS",
    [
      ["Physical Infrastructure", "CSP", "CSP"],
      ["Virtualization / Servers / Storage / Networking", "CSP (+ some shared)", "CSP"],
      ["Operating System", "User", "CSP"],
      ["Middleware & Runtime", "User", "CSP"],
      ["Application Security", "User", "User (IaaS) / CSP (SaaS)"],
      ["Identity & Access Management", "User", "Shared"],
      ["Data Security & Encryption", "User", "User (for own data)"],
      ["Endpoint Security", "User", "Both"],
      ["Network Flow Controls", "Both (User configures firewall)", "CSP"],
    ]
  ), sp(),
  h3("IaaS Security (e.g., AWS EC2, Microsoft Azure VM):"),
  bulB("CSP", "Secures physical data center, hardware, networking, and hypervisor layer. Provides secure OS images and infrastructure redundancy."),
  bulB("Customer", "Responsible for: OS security (patches, updates), Identity & Access Management (IAM), Application security, Middleware and APIs, Data protection and encryption, Configuring firewall rules (Security Groups), Network policies (VPC, NAT, inbound/outbound rules)."),
  h3("PaaS Security (e.g., AWS Elastic Beanstalk, Google Kubernetes Engine):"),
  bulB("CSP", "Manages and secures the platform layer including middleware, servers, runtime environments, and network security."),
  bulB("Customer", "Responsible for: Securing application code and APIs, Data security (encryption at rest and in transit), Monitoring and logging development lifecycle events, Configuring IAM policies and permissions."),
  bulB("Shared", "Identity and Access Management – CSP provides identity tools; users configure policies."),
  h3("SaaS Security (e.g., Gmail, Office 365, Salesforce, Dropbox):"),
  bulB("CSP", "Manages nearly all security: infrastructure, platform, application, DDoS protection, WAFs."),
  bulB("Customer", "Primarily responsible for: Data security (what data is stored and shared), Access control (who can use the application), Secure login credentials management."),
  h3("Real-World Example – AWS Shared Responsibility Model:"),
  p("AWS defines the division as: 'Security OF the cloud' (AWS responsibility) vs 'Security IN the cloud' (Customer responsibility)."),
  bulB("AWS's Responsibility", "Hardware, software, networking, and facilities running AWS Cloud services. Physical security of data centers (inherited controls)."),
  bulB("Customer's Responsibility (EC2)", "Configure Security Groups (firewall rules for inbound/outbound traffic), manage secure access through PKI and keys, maintain the guest OS (updates, patches)."),
  bulB("Customer's Responsibility (S3)", "Configure IAM policies to control access to stored data. AWS manages OS and infrastructure."),
  bulB("Shared Controls", "Patch management, configuration management, identity management, logging and monitoring."),
  h3("Azure Shared Responsibility Model:"),
  bulB("Microsoft's Responsibility", "Infrastructure layer: physical data centers, servers, and underlying network infrastructure."),
  bulB("Customer's Responsibility", "Own data, identities, and endpoint devices."),
  bulB("Shared", "Applications, IAM, network controls, operating systems – Azure provides tools, users configure and manage."),
  h3("Google Cloud Shared Responsibility (Shared Fate):"),
  bulB("IaaS", "Google secures infrastructure; users accountable for OS, apps, IAM, data protection."),
  bulB("PaaS", "Users handle app security and IAM; Google takes broader responsibilities for network, storage, and encryption."),
  bulB("SaaS", "Google manages the majority of security; users responsible only for data security and access management."),
  hr(),

  // Q3
  qHead(3, 10, "Explain the economics of cloud computing, including CAPEX vs OPEX."),
  h3("Overview:"),
  p("The economics of cloud computing refers to the financial transformation enabled by cloud services – shifting IT spending from large, one-time capital investments to flexible, usage-based operational expenses. The primary drivers are economies of scale and simplified software delivery and operations."),
  h3("Capital Expenditure (CAPEX) in Traditional IT:"),
  p("Capital costs are one-time expenses incurred in acquiring long-term assets useful in production or service delivery. In traditional IT, enterprises owned data centers, servers, storage, and software licenses – all capital assets."),
  p("Traditional IT capital costs included:"),
  bul("Purchase of servers, storage hardware, networking equipment"),
  bul("Software licenses (one-time, per-user, or per-server pricing)"),
  bul("Data center space, cooling systems, power infrastructure"),
  bul("IT department salaries and support centers"),
  bul("Hardware maintenance and technical support contracts"),
  p("Problems with CAPEX-based IT:"),
  bulB("Depreciation", "IT assets (servers, software) lose value over time through hardware aging and software obsolescence, directly reducing enterprise revenues."),
  bulB("Over-provisioning", "Enterprises buy for peak capacity, leaving resources idle most of the time."),
  bulB("Long procurement cycles", "Hardware purchases require planning months in advance, limiting agility."),
  bulB("High barrier to entry", "Startups and SMEs struggle to afford large upfront IT investments."),
  h3("Operational Expenditure (OPEX) in Cloud Computing:"),
  p("Cloud computing transforms CAPEX into OPEX – enterprises pay only for what they use, on a pay-as-you-go basis."),
  p("Benefits of OPEX-based cloud model:"),
  bulB("Reduced Capital Costs", "Eliminates the need to purchase expensive IT infrastructure."),
  bulB("No Depreciation", "Enterprises no longer own depreciating hardware or software assets."),
  bulB("Subscription-based Software", "Replaces costly one-time licenses with flexible subscriptions (SaaS)."),
  bulB("Lower Maintenance Costs", "Cloud providers handle updates, scaling, backups, security – reducing in-house IT burden."),
  bulB("Reduced Administrative Costs", "Fewer IT staff required for infrastructure management."),
  bulB("Scalability", "Pay for more resources only when needed; scale down when demand drops."),
  h3("Cloud Pricing Models:"),
  h3("(a) Tiered Pricing:"),
  p("Services offered in predefined tiers, each with a fixed computing specification and SLA. Each tier has a specific cost per unit of time."),
  bulB("Example", "Amazon EC2 provides different server configurations (CPU type, speed, memory) at different hourly rates. A t3.micro costs significantly less than an m5.4xlarge."),
  h3("(b) Per-Unit Pricing:"),
  p("Customers charged based on units of specific services consumed – data transfer, storage, or memory allocation."),
  bulB("Example", "GoGrid charges by RAM/hour for deployed servers. AWS S3 charges per GB of storage and per GB of data transfer."),
  h3("(c) Subscription-Based Pricing:"),
  p("Mostly used by SaaS providers. Customers pay recurring monthly/annual fees for software access."),
  bulB("Example", "Microsoft 365 charges per user per month. Salesforce CRM has monthly subscription tiers."),
  h3("CAPEX vs OPEX Comparison:"),
  sp(), tbl("CAPEX (Traditional IT)", "OPEX (Cloud Computing)",
    [
      ["Large upfront investment required", "Pay-as-you-go; no upfront cost"],
      ["Assets depreciate over time", "No depreciation – pay for service used"],
      ["Fixed capacity (risk of over/under provisioning)", "Elastic capacity – scales with demand"],
      ["Long procurement and setup time", "Resources provisioned in minutes"],
      ["High barrier to entry for startups", "Startups access global infrastructure instantly"],
      ["IT team manages infrastructure", "Cloud provider handles updates, maintenance, security"],
      ["Predictable but inflexible spending", "Variable but aligned to business needs"],
    ]
  ), sp(),
  h3("Special Case – Startups:"),
  p("For startups, cloud provides a complete digital foundation without upfront investment. A startup can access: IT infrastructure (servers, storage, networking), Software development platforms, CRM and ERP systems – all immediately and at operational scale, focusing on growth and innovation rather than IT spending."),
  hr(),

  // Q4.a
  qHead("4.a", 5, "Explain cloud interoperability and the need for standards."),
  h3("Cloud Interoperability:"),
  p("Cloud interoperability is the ability of different cloud systems, platforms, and services from multiple vendors to work together seamlessly, allowing data, applications, and workloads to be moved or shared across cloud environments without significant modification, re-coding, or high migration costs."),
  p("Goals of interoperability:"),
  bulB("Data Portability", "Move data between clouds without format conversion or data loss."),
  bulB("Application Portability", "Deploy and run applications across different cloud providers using the same code."),
  bulB("Service Integration", "Connect cloud services from different providers into unified workflows."),
  bulB("Avoid Vendor Lock-in", "Allow enterprises to switch providers based on cost, performance, or compliance needs."),
  h3("Current State of Interoperability:"),
  bulB("IaaS Interoperability", "Major challenge: proprietary virtual machine formats. OVF (Open Virtualization Format) provides platform-independent VM packaging, but is currently supported by only a few vendors and mostly used for static VM images, not live migration."),
  bulB("API Fragmentation", "APIs remain vendor-specific. In IaaS, AWS is dominant and many open-source IaaS providers adopt AWS-compatible APIs, but no universal standard exists."),
  h3("Need for Standards:"),
  p("The current situation resembles the early Internet era, when organizations used isolated, non-standardized networks. Progress toward standardization has begun but remains limited."),
  p("Why standards are needed:"),
  bulB("Prevent Vendor Lock-in", "Vendor lock-in occurs when customers cannot easily switch providers due to proprietary technologies or high migration costs. Standards reduce this risk."),
  bulB("Enable Competition", "Common standards allow smaller providers to compete with established giants by offering compatible services."),
  bulB("Simplify Multi-Cloud Deployments", "Standards enable enterprises to distribute workloads across multiple clouds without compatibility issues."),
  bulB("Security & Compliance", "Standardized security frameworks ensure consistent protection and regulatory compliance across providers."),
  bulB("Cost Efficiency", "Avoiding re-engineering costs when switching or integrating cloud services."),
  h3("Key Standardization Initiatives:"),
  bulB("Cloud Computing Interoperability Forum (CCIF)", "Promotes open interoperability standards."),
  bulB("Open Cloud Consortium", "Supports cloud research and data-intensive applications."),
  bulB("DMTF Cloud Standards Incubator", "Works on cloud management and interoperability specifications."),
  bulB("Open Cloud Manifesto", "Collaborative effort highlighting benefits of open standards."),
  bulB("Open Virtualization Format (OVF)", "Platform-independent specification for packaging and distributing VM images."),
  hr(),

  // Q4.b
  qHead("4.b", 5, "Explain scalability in cloud computing and its types."),
  h3("Definition:"),
  p("Scalability is the capability of a cloud system to grow and handle increased workloads without performance degradation, while maintaining the same or better quality of service."),
  p("In cloud computing, scalability is achieved through cloud middleware designed to scale along multiple dimensions."),
  h3("Types of Scalability:"),
  h3("1. Vertical Scalability (Scale Up):"),
  p("Adding more power to an existing machine – increasing CPU, memory, or storage on the same physical/virtual server."),
  bulB("Advantages", "Simple to implement; no application changes required; immediate performance boost."),
  bulB("Disadvantages", "Limited by hardware maximums; results in downtime during upgrade; costly at high-end."),
  bulB("Example", "Upgrading an AWS EC2 instance from t3.medium (2 vCPUs, 4 GB RAM) to t3.xlarge (4 vCPUs, 16 GB RAM)."),
  h3("2. Horizontal Scalability (Scale Out):"),
  p("Adding more machines (instances or nodes) to the resource pool to distribute the workload."),
  bulB("Advantages", "No hardware limits; highly elastic; no downtime during scaling; cost-efficient."),
  bulB("Disadvantages", "Application must support distributed architecture; load balancing complexity."),
  bulB("Example", "AWS Auto Scaling adding EC2 instances during peak traffic and terminating them when demand drops."),
  h3("3. Performance Scalability:"),
  p("The ability to handle higher computational workloads efficiently. Cloud middleware must process more requests per second without degradation as load grows."),
  bulB("Example", "A database cluster handling 1000 queries/second scaling to 10,000 queries/second by distributing reads across multiple replicas."),
  h3("4. Size Scalability:"),
  p("Ability to add more physical or virtual resources (compute nodes, storage systems) seamlessly into the existing infrastructure."),
  bulB("Example", "Amazon S3 automatically expanding storage capacity without user intervention as data grows."),
  h3("5. Load Scalability:"),
  p("Ability to dynamically balance workloads across distributed resources, preventing bottlenecks and ensuring even resource utilization."),
  bulB("Example", "Elastic Load Balancers (ELBs) in AWS distributing incoming HTTP requests across multiple EC2 instances."),
  h3("Importance of Scalability in Cloud:"),
  bul("Enterprises gain access to virtually unlimited computing power without capital investment."),
  bul("Businesses can handle demand spikes (e.g., e-commerce during festive sales) without pre-purchasing idle capacity."),
  bul("Pay only for what is used – aligned with the pay-as-you-go economic model."),
  hr(),

  // Q5
  qHead(5, 10, "Explain the importance of energy efficiency in cloud data centers."),
  h3("Introduction:"),
  p("Modern cloud data centers host a wide range of applications – from short-lived requests (e-commerce, social networking) to long-running jobs (simulations, large dataset processing). These applications share hardware resources, creating challenges in on-demand resource provisioning and dynamic workload management."),
  h3("The Problem: Energy Crisis in Data Centers:"),
  bulB("Traditional Approach", "Resources are statically allocated based on peak load demand. This ensures performance isolation and guarantees, but wastes energy when workloads are low."),
  bulB("Energy Consumption Scale", "A typical data center consumes as much energy as 25,000 households. Energy costs of powering data centers double every 5 years."),
  bulB("Carbon Emissions", "Data center carbon emissions exceed those of entire countries like Argentina and the Netherlands."),
  bulB("Financial Impact on Providers", "Amazon estimates 42% of its data center budget is energy-related (direct electricity + cooling amortized over 15 years). Rising costs threaten profit margins."),
  h3("Industry Responses:"),
  bulB("Geographic Location", "Companies like Google, Microsoft, and Yahoo! are building data centers near the Columbia River (USA) to exploit cheap hydroelectric power and in desert areas for natural cooling."),
  bulB("The Green Grid", "Leading IT vendors formed this global consortium focused on promoting energy-efficient data centers and minimizing environmental impact."),
  bulB("Future Outlook (Pike Research)", "Worldwide data center energy expenditures projected to drop from $23.3B (2010) to $16.0B (2020). GHG emissions expected to see a 28% reduction due to cloud adoption."),
  h3("The Shift: Green Cloud Computing:"),
  p("The focus must shift from performance-only optimization to energy-efficient optimization while maintaining service-level performance."),
  h3("Vision of Green Cloud Computing:"),
  bulB("Goal", "Ensure future growth of cloud computing is sustainable."),
  bulB("Focus", "Efficient processing (better compute resource use), optimized infrastructure utilization, minimizing energy consumption while meeting service demands."),
  bulB("Market-Based Utility Models", "Only accept requests that can be fulfilled efficiently – maximize revenue while ensuring energy efficiency."),
  h3("Energy-Efficient and Green Cloud Architecture (4 components):"),
  h3("1. Consumers / Brokers:"),
  p("Cloud consumers (companies) or their brokers submit service requests. Consumer = entity requesting cloud resources; User = end-user of the deployed application."),
  h3("2. Green Resource Allocator (Core Component):"),
  p("Acts as the interface between consumers and cloud infrastructure, managing both QoS requirements and energy efficiency. Sub-components:"),
  bulB("Green Negotiator", "Handles SLA negotiations (QoS, price, penalties)."),
  bulB("Service Analyzer", "Analyzes service requirements; uses input from VM Manager and Energy Monitor."),
  bulB("Consumer Profiler", "Tracks consumer characteristics and prioritizes premium clients."),
  bulB("Pricing Module", "Dynamic pricing to balance supply and demand."),
  bulB("Energy Monitor", "Observes physical machines and decides when to power servers on/off."),
  bulB("Service Scheduler", "Assigns requests to VMs; adds/removes VMs for workload changes."),
  bulB("VM Manager", "Tracks VM availability; migrates VMs across physical servers for load balancing and energy optimization."),
  bulB("Accounting", "Monitors actual resource usage; computes costs; uses historical data to improve allocation."),
  h3("3. Virtual Machines (VMs):"),
  p("Multiple VMs can be started/stopped dynamically. Each VM can run different OS/applications concurrently."),
  p("Energy efficiency techniques:"),
  bulB("VM Consolidation", "Pack workloads onto fewer servers to reduce active machine count."),
  bulB("Dynamic VM Migration", "Move VMs to reduce idle resources."),
  bulB("Dynamic Voltage and Frequency Scaling (DVFS)", "Lower CPU frequency/voltage when full performance is not required."),
  h3("4. Physical Machines:"),
  p("The actual hardware servers. Provide virtualized resources for service demands. Can be powered on/off or set to low-power states based on workloads."),
  h3("Energy-Aware Dynamic Resource Allocation:"),
  p("Virtualization is the foundation for energy-efficient resource management. It allows dynamic migration of VMs across physical nodes based on QoS requirements."),
  p("VM Consolidation benefits:"),
  bul("Unused VMs are logically resized and consolidated onto fewer physical nodes."),
  bul("Idle servers can be turned off or put into hibernation."),
  bul("Increases utilization → reduces total number of active servers → lower energy consumption."),
  h3("InterClouds and Energy Efficiency:"),
  p("Cloud providers (e.g., Amazon EC2) operate multiple data centers worldwide. The InterCloud concept connects these for energy-efficient load shifting:"),
  bulB("Electricity Price Variation", "Electricity prices vary with time of day and local weather conditions; routing to cheaper locations saves cost."),
  bulB("Renewable Energy Sources", "Different sites use coal, hydro, wind, solar – routing to renewable sources minimizes carbon footprint."),
  bulB("Challenges", "Latency from remote data centers, energy cost of data transfers, intermittency of renewable sources."),
  hr(),

  // Q6
  qHead(6, 10, "Analyze the benefits and challenges of federated cloud environments."),
  h3("Definition:"),
  p("Cloud Federation and InterCloud are mechanisms that allow different Cloud providers to interoperate, enabling market-oriented Cloud computing (resource trading, workload shifting, service sharing). Agreements between independent providers allow them to share resources and services in a privileged manner."),
  h3("Cloud Federation Reference Stack (3 Levels):"),
  h3("1. Conceptual Level:"),
  p("Focuses on why Clouds should federate."),
  bulB("Motivations", "Cost savings, scalability, better availability."),
  bulB("Advantages", "Resource pooling, better SLAs."),
  bulB("Opportunities", "New services, global reach."),
  bulB("Obligations", "Responsibilities and compliance among providers."),
  h3("2. Logical and Operational Level:"),
  p("Focuses on how federation works functionally."),
  bulB("Federation Model", "Rules of collaboration between providers."),
  bulB("Cloud Service & Provider Agreements", "Contracts, access rules, sharing policies."),
  bulB("Market & Pricing Models", "Cost sharing, billing, pay-per-use mechanisms."),
  bulB("SLAs", "Performance, reliability, and security guarantees."),
  h3("3. Infrastructural Level:"),
  p("Technical foundation enabling interoperability."),
  bulB("Protocols, Interfaces & Standards", "Open APIs, standard communication."),
  bulB("Programmatic Interoperation", "Software/middleware enabling cross-Cloud operations."),
  bulB("Federation Platforms", "Frameworks like RESERVOIR and InterCloud."),
  h3("Benefits of Federated Cloud Environments:"),
  h3("1. Performance & Reliability:"),
  bul("Spreading services across multiple data centers improves resilience and reduces latency for users."),
  bul("If one provider's data center fails, workloads can be shifted to another federated provider."),
  bul("Better SLA compliance through geographic distribution."),
  h3("2. Energy Efficiency & Cost Savings:"),
  bul("Electricity prices vary with time of day and local weather conditions."),
  bul("Different sites use different energy sources (coal, hydro, wind, solar), each with its own environmental impact."),
  bul("By shifting loads between locations, providers can reduce costs and minimize carbon footprint."),
  bul("Access to cheap energy sources (hydroelectric, solar) at specific geographic locations."),
  h3("3. Scalability Beyond Single Provider Limits:"),
  bul("A provider at capacity can offload workloads to partner federated providers."),
  bul("Customers get virtually unlimited scale without hitting single-provider capacity ceilings."),
  h3("4. Market Efficiency:"),
  bul("Market-oriented cloud computing enables competitive resource pricing."),
  bul("Providers can buy/sell excess compute capacity, improving overall utilization."),
  bul("Enables workload shifting based on real-time demand and cost."),
  h3("5. Business Continuity:"),
  bul("Geographic distribution across federated providers ensures disaster recovery."),
  bul("Workloads automatically migrate to healthy providers if one fails."),
  h3("Challenges of Federated Cloud Environments:"),
  h3("1. Latency & Delay Costs:"),
  p("Routing requests to remote data centers increases response time. Applications with strict latency requirements (e.g., real-time gaming, video calls) may suffer in federated environments."),
  h3("2. Energy Cost of Data Transfers:"),
  p("Transferring large volumes of data across the Internet between federated providers consumes additional energy. This can offset the energy savings from geographic load shifting."),
  h3("3. Intermittency of Renewables:"),
  p("Renewable energy sources (wind, solar) are not always available, making real-time routing decisions for energy efficiency complex and unpredictable."),
  h3("4. Standardization Gap:"),
  p("Different providers use proprietary APIs, VM formats, and SLAs. Lack of universal standards makes seamless federation technically challenging. OVF helps with VM portability but doesn't yet support live migration across providers."),
  h3("5. Security & Trust:"),
  p("Sharing resources between independent providers raises authentication, authorization, and data privacy concerns. Federated identity management must ensure access controls are consistent across provider boundaries."),
  h3("6. Financial Complexity:"),
  p("Since cloud services are pay-per-use, federation involves financial agreements between providers. Billing, cost allocation, and dispute resolution across multiple providers are complex."),
  h3("7. Compliance & Governance:"),
  p("Data moving across federated providers in different regions must comply with local regulations (GDPR, HIPAA). Ensuring consistent compliance across federated environments is difficult."),
  hr(),

  // Q7.a
  qHead("7.a", 5, "Explain cloud computing security and its key objectives."),
  h3("Definition:"),
  p("Cloud computing security (cloud security) is a comprehensive set of strategies, technologies, policies, and controls designed to protect cloud-hosted data centers, applications, and resources from cyberattacks, unauthorized access, data breaches, and service disruptions."),
  p("According to Gartner: \"Cloud security refers to the processes, mechanisms, and services used to control the security, compliance, and other usage risks of cloud computing.\""),
  h3("Why Cloud Security is Critical:"),
  bul("Data and applications have moved from local servers to distributed cloud environments accessible over the internet."),
  bul("Multi-tenant architectures increase the attack surface."),
  bul("87% of online shoppers rely on social media to influence purchases – making cloud-hosted e-commerce a prime target."),
  bul("Cybercriminals generate nearly $3 billion annually by exploiting cloud platform vulnerabilities."),
  h3("Key Objectives of Cloud Security:"),
  h3("1. Confidentiality:"),
  p("Ensures that data is accessible only to authorized parties. Prevents unauthorized disclosure of sensitive information."),
  bulB("Implementation", "Encryption (AES, RSA), IAM with role-based access control, VPNs."),
  bulB("Example", "Encrypting customer payment data stored in cloud databases."),
  h3("2. Integrity:"),
  p("Guarantees that data is not altered, corrupted, or tampered with during storage or transmission."),
  bulB("Implementation", "Hash functions (SHA-256), digital signatures, checksums."),
  bulB("Example", "File integrity monitoring ensures database records are not modified without authorization."),
  h3("3. Availability:"),
  p("Ensures cloud services and data are accessible when needed. Prevents service disruptions."),
  bulB("Implementation", "Redundant systems, load balancers, DDoS protection, disaster recovery plans."),
  bulB("Example", "AWS availability zones ensure services remain up even if one data center fails."),
  h3("4. Authentication:"),
  p("Verifies the identity of users, systems, and applications before granting access."),
  bulB("Implementation", "Multi-Factor Authentication (MFA), PKI, SSO (Single Sign-On), OAuth."),
  bulB("Example", "Requiring both password and OTP before accessing cloud management console."),
  h3("5. Authorization:"),
  p("Ensures authenticated users can only access resources they are permitted to use."),
  bulB("Implementation", "Role-Based Access Control (RBAC), Attribute-Based Access Control (ABAC), Least Privilege Principle."),
  bulB("Example", "A developer can read S3 buckets but cannot delete EC2 instances."),
  h3("6. Nonrepudiation:"),
  p("Ensures that parties cannot deny their actions (e.g., sending a message, making a transaction)."),
  bulB("Implementation", "Digital signatures, audit logs, blockchain."),
  bulB("Example", "Digital signatures on financial transactions in cloud-hosted banking apps."),
  h3("7. Accountability:"),
  p("Tracking and controlling all user activities in the cloud environment."),
  bulB("Implementation", "Cloud audit logs, CloudTrail (AWS), Azure Monitor, SIEM systems."),
  hr(),

  // Q7.b
  qHead("7.b", 5, "Apply these security principles to a cloud computing scenario."),
  h3("Scenario: An E-Commerce Company (ShopNow) migrates to AWS Cloud"),
  p("ShopNow is an e-commerce company that migrates its entire platform to AWS, hosting its web application, customer database, and payment processing system on the cloud. Let us apply each security principle:"),
  h3("1. Confidentiality:"),
  bulB("Application", "ShopNow encrypts all customer payment data stored in Amazon RDS using AES-256 encryption. IAM policies ensure only the payment processing service can access the payment database."),
  bulB("Tool Used", "AWS KMS (Key Management Service) for encryption key management; VPCs to isolate sensitive workloads."),
  h3("2. Integrity:"),
  bulB("Application", "ShopNow uses digital signatures to verify order details before processing. CloudTrail logs every API call, and hash checks verify that product data in DynamoDB has not been tampered with."),
  bulB("Tool Used", "AWS CloudTrail for audit logging; S3 Object Lock for preventing modification."),
  h3("3. Availability:"),
  bulB("Application", "ShopNow deploys across multiple AWS Availability Zones. Elastic Load Balancers distribute traffic. AWS Shield protects against DDoS attacks during peak sales seasons."),
  bulB("Tool Used", "AWS Auto Scaling, AWS Shield, Route 53 for failover routing."),
  h3("4. Authentication:"),
  bulB("Application", "ShopNow requires all admin users to use MFA when accessing the AWS Management Console. Customer logins use Amazon Cognito with OTP-based two-factor authentication."),
  bulB("Tool Used", "AWS IAM MFA, Amazon Cognito for user authentication."),
  h3("5. Authorization:"),
  bulB("Application", "ShopNow implements RBAC using AWS IAM. Developers have read access to production logs but cannot modify production databases. Finance team can access billing reports only."),
  bulB("Tool Used", "AWS IAM Roles and Policies following Least Privilege Principle."),
  h3("6. Nonrepudiation:"),
  bulB("Application", "All purchase transactions are signed with digital signatures. AWS CloudTrail records every API call with timestamp, user identity, and source IP – ensuring no user can deny their actions."),
  bulB("Tool Used", "AWS CloudTrail, digital signatures on payment confirmations."),
  h3("7. Accountability:"),
  bulB("Application", "ShopNow uses Amazon GuardDuty for continuous threat detection and AWS Config to audit resource configurations. Security alerts are sent to the CISO when anomalous access is detected."),
  bulB("Tool Used", "Amazon GuardDuty, AWS Config, AWS Security Hub."),
  h3("Shared Responsibility Applied:"),
  bulB("AWS Responsibility", "Physical security of data centers, hypervisor isolation, global network infrastructure."),
  bulB("ShopNow's Responsibility", "OS patching on EC2, configuring Security Groups, managing IAM users, encrypting customer data, application security."),
  hr(),

  // Q8.a
  qHead("8.a", 5, "Explain cloud security architecture with a neat diagram description."),
  h3("Overview:"),
  p("The Cloud Security Architecture builds on the Cloud Computing Reference Architecture and defines security responsibilities at each service layer through the Shared Responsibility Model (SRM) between Cloud Service Providers (CSPs) and Users. Major providers (AWS, Azure, GCP) all follow this model."),
  h3("Cloud Security Architecture Layers (Bottom to Top):"),
  h3("1. System Infrastructure (Bottom Layer – IaaS):"),
  p("Covers physical servers, networks, storage hardware, racks, and cooling systems."),
  p("Security measures:"),
  bulB("Physical Security", "Data center surveillance, biometric access, perimeter fencing."),
  bulB("Hardware Security", "Tamper-proof servers, secure boot processes, hardware security modules (HSMs)."),
  bulB("Disaster Recovery", "Geographic redundancy, backup power systems, data replication."),
  h3("2. Core Middleware (Cloud Resources + Hypervisor Layer):"),
  p("The virtualization and compute platform layer."),
  bulB("Hypervisor Security", "VM isolation, machine instruction set security, VM data protection, disk encryption."),
  bulB("Compute Security", "Secure access to VMs via SSH, RDP, PKI, strong passwords."),
  bulB("Network Security", "Security Groups (inbound/outbound rules), VPC, NAT rules, firewalls."),
  bulB("Storage Security", "IAM for object storage access control, disk encryption for block storage."),
  bulB("OS Security", "CSP provides secure OS images free from known vulnerabilities."),
  bulB("AAA Security", "Authentication, Authorization, Accounting with IAM policies; define user roles, access permissions."),
  h3("3. Cloud Hosting Platforms (PaaS Layer):"),
  p("Application development and hosting environment."),
  bulB("Application Code Security", "Protect source code, repositories, container images; secure DevOps/CI-CD workflows."),
  bulB("Data Security", "Encrypt data at rest and in transit; monitor and log all activities."),
  bulB("API Security", "Secure REST APIs over HTTPS; ensure no leakage during integrations."),
  bulB("Auditability", "Logging and monitoring of development lifecycle events."),
  h3("4. Cloud Applications (SaaS Layer – Top Layer):"),
  p("End-user applications delivered via cloud (e.g., Gmail, Office 365, Salesforce)."),
  bulB("Endpoint Security", "Secure user devices accessing SaaS applications."),
  bulB("Web Application Security", "WAFs defending against SQL injection, XSS, CSRF."),
  bulB("Data Security", "Protect user data and sensitive information from unauthorized access."),
  bulB("DDoS Protection", "Intelligent filtering to keep services available."),
  h3("Cross-cutting Security Concerns (Applied at All Layers):"),
  bulB("Identity & Access Management (IAM)", "Applied across all layers – authentication, authorization, role-based access."),
  bulB("Risk & Compliance", "Regulatory compliance (GDPR, HIPAA, PCI-DSS) monitored across all layers."),
  hr(),

  // Q8.b
  qHead("8.b", 5, "Explain the cloud shared responsibility model."),
  p("(See detailed answer in Q2 – 10 marks. Summary version below.)"),
  h3("Definition:"),
  p("The Shared Responsibility Model (SRM) is a cloud security framework defining which security tasks are the responsibility of the CSP and which are the Customer's, depending on the service model (IaaS, PaaS, SaaS)."),
  bulB("CSP", "Secures the cloud infrastructure (data centers, hardware, virtualization, networking)."),
  bulB("Customer", "Secures what they deploy in the cloud (apps, data, identities, configurations)."),
  h3("Across Service Models:"),
  bulB("IaaS (e.g., AWS EC2, Azure VM)", "CSP: physical infra + hypervisor. Customer: OS, apps, IAM, data, firewall configuration."),
  bulB("PaaS (e.g., Google App Engine, AWS Beanstalk)", "CSP: platform, middleware, runtime, network. Customer: app code, APIs, data. IAM: shared."),
  bulB("SaaS (e.g., Gmail, Salesforce, Dropbox)", "CSP: nearly everything. Customer: data security and access control only."),
  h3("Key Principle:"),
  p("As you move from IaaS → PaaS → SaaS, the CSP takes on more security responsibility, and the Customer's responsibility decreases. However, data security and access management always remain the customer's responsibility regardless of the service model."),
  h3("Azure Example:"),
  bulB("Microsoft's Responsibility", "Physical data centers, servers, underlying network infrastructure."),
  bulB("Customer's Responsibility", "Own data, identities, endpoint devices."),
  bulB("Shared", "Applications, IAM, network controls, OS – tools provided by Azure, configured by customer."),
  h3("AWS Example:"),
  bulB("AWS Responsibility (EC2)", "Physical security, hypervisor, global networking."),
  bulB("Customer Responsibility (EC2)", "Security Groups (firewall rules), PKI/keys, guest OS patching."),
  bulB("Inherited Controls", "Customers inherit physical security measures managed by AWS."),
  hr(),

  // Q9.a
  qHead("9.a", 5, "Explain the need for standards in cloud computing."),
  h3("Current Situation:"),
  p("The current state of cloud computing standards resembles the early Internet era, when organizations used isolated, non-standardized networks. Progress toward standardization has begun, but remains limited. Today, APIs remain vendor-specific, VM formats are proprietary, and compatibility between providers is very limited."),
  h3("Why Standards are Needed:"),
  h3("1. Prevent Vendor Lock-in:"),
  p("Vendor lock-in occurs when customers cannot easily switch providers due to proprietary technologies or high migration costs. Risks include:"),
  bul("Customer finding a better alternative but being trapped with the current provider."),
  bul("Vendor failing to deliver required services, leaving the customer with limited options."),
  p("Standards allow enterprises to switch providers seamlessly, increasing market competition."),
  h3("2. Enable Interoperability:"),
  p("Different cloud providers must be able to work together. A federated cloud environment requires standardized interfaces, APIs, and data formats to enable resource sharing, workload migration, and integrated service delivery."),
  h3("3. Ensure Portability:"),
  p("Applications and data must be portable across different cloud environments."),
  bulB("Open Virtualization Format (OVF)", "Provides a platform-independent specification for packaging and distributing VM images. Currently limited to static VM images – live migration across providers remains a challenge."),
  h3("4. Facilitate Fair Competition:"),
  p("Without standards, large established providers (AWS, Azure, GCP) dominate because their proprietary ecosystems create high switching costs. Standards level the playing field, enabling smaller providers to compete."),
  h3("5. Security and Compliance:"),
  p("Standardized security frameworks (NIST, ISO 27001, CSA) ensure consistent protection policies across providers. Compliance with regulations (GDPR, HIPAA, PCI-DSS) becomes easier with common standards."),
  h3("6. Simplify Multi-Cloud Deployments:"),
  p("Enterprises using multiple cloud providers face integration challenges. Standards enable seamless data exchange, API integration, and workload distribution without re-engineering for each provider."),
  h3("Key Standardization Efforts:"),
  bulB("Cloud Computing Interoperability Forum (CCIF)", "Promotes open interoperability."),
  bulB("Open Cloud Consortium", "Supports data-intensive cloud research."),
  bulB("DMTF Cloud Standards Incubator", "Cloud management specifications."),
  bulB("Open Cloud Manifesto", "Advocates for open cloud standards."),
  bulB("AWS-Compatible APIs", "Many open-source IaaS providers adopt AWS-compatible APIs for compatibility."),
  hr(),

  // Q9.b
  qHead("9.b", 5, "Analyze the role of Identity and Access Management (IAM) in cloud security."),
  h3("Definition:"),
  p("Identity and Access Management (IAM) is a framework of policies, technologies, and processes to manage who can access what cloud resources, when, and under what conditions. It is similar to the AAA model (Authentication, Authorization, Accounting) in traditional network security."),
  h3("Core Functions of IAM:"),
  h3("1. Authentication (Who are you?):"),
  p("Verifies the identity of users, applications, and services before granting access."),
  bulB("Methods", "Passwords, MFA (Multi-Factor Authentication), biometrics, PKI certificates, SSO (Single Sign-On)."),
  bulB("Example", "AWS IAM requires MFA for root account access. Azure AD uses conditional access policies."),
  h3("2. Authorization (What can you do?):"),
  p("Determines what authenticated users or systems are permitted to access or perform."),
  bulB("RBAC (Role-Based Access Control)", "Access based on assigned roles (e.g., Developer, Admin, Read-Only)."),
  bulB("ABAC (Attribute-Based Access Control)", "Access based on attributes (e.g., department, location, time of day)."),
  bulB("Least Privilege Principle", "Users are given only the minimum permissions required for their tasks."),
  bulB("Example", "A developer can deploy applications to staging but not production. Finance team can view billing but not EC2 instances."),
  h3("3. Accounting/Auditing (What did you do?):"),
  p("Tracks and records all user activities for audit trails, compliance reporting, and anomaly detection."),
  bulB("Implementation", "AWS CloudTrail logs every API call. Azure Monitor tracks all resource changes."),
  bulB("Example", "If a data breach occurs, CloudTrail logs allow security teams to trace exactly which user accessed which resource and when."),
  h3("IAM Components in Cloud:"),
  bulB("Policies", "JSON/YAML documents defining what actions are allowed or denied on which resources."),
  bulB("Roles", "Temporary identities assigned to users or services for specific tasks."),
  bulB("Groups", "Collections of users sharing the same access permissions."),
  bulB("Service Accounts", "Machine identities used by applications to authenticate with cloud services."),
  h3("IAM Challenges in Cloud:"),
  bulB("Scale", "Designing and managing roles across thousands of users and services is complex."),
  bulB("Credential Rotation", "Regular rotation of access keys and secrets to prevent compromise."),
  bulB("Least Privilege Enforcement", "Ensuring users don't accumulate excessive permissions over time (Permission Creep)."),
  bulB("Multi-Cloud IAM", "Ensuring consistent identity and access policies across AWS, Azure, GCP simultaneously."),
  bulB("Privileged Access Management (PAM)", "Securing admin/root accounts with extra controls to prevent misuse."),
  h3("IAM Best Practices:"),
  bul("Enable MFA for all privileged accounts."),
  bul("Implement Least Privilege – grant only necessary permissions."),
  bul("Regularly audit and review IAM policies and role assignments."),
  bul("Rotate access keys and credentials regularly."),
  bul("Use IAM roles instead of long-term access keys for applications."),
  bul("Monitor and log all IAM activity with SIEM tools."),
  hr(),

  // Q10
  qHead(10, 10, "Explain security issues in different cloud deployment models."),
  h3("Overview:"),
  p("Different cloud deployment models – Private, Public, and Hybrid – have distinct security characteristics, risks, and challenges. Understanding these helps organizations choose the right model and implement appropriate security controls."),
  h3("1. Private Cloud Security:"),
  p("Private clouds are dedicated environments designed for a single tenant or organization, operating behind the organization's own firewall. While they offer stronger control and visibility, they are not immune to security risks."),
  h3("Security Issues in Private Clouds:"),
  bulB("a) Physical Security Gaps", "Unlike large CSPs with redundant, geographically distributed data centers, many organizations lack robust surveillance systems, fire protection, and restricted access controls. Physical vulnerabilities can lead to theft, data loss, or service outages."),
  bulB("b) Insider Threats", "Privileged administrators with access to private cloud resources can intentionally or accidentally cause breaches. Insider knowledge of internal systems makes detection difficult."),
  bulB("c) Infrastructure Security Management", "Enterprises must actively implement layered security controls: hypervisor security, OS security, storage security, platform security, and IAM."),
  bulB("d) Data Loss or Leakage", "Hardware failures, natural disasters, misconfigurations, or weak disaster recovery mechanisms can result in permanent data loss."),
  bulB("e) Inadequate Access Controls", "Misconfigured access policies or weak privilege management enable unauthorized access to sensitive workloads."),
  bulB("f) Malware & External Attacks", "Private clouds remain exposed to malware, DDoS attacks, and targeted exploits – especially if perimeter defenses are weak."),
  bulB("g) Patch Management Gaps", "Delays in applying patches to virtualization software, OS, or applications leave unaddressed vulnerabilities."),
  bulB("h) Compliance & Regulatory Challenges", "Private clouds hosting sensitive data must comply with HIPAA, GDPR, PCI-DSS. Failure to enforce standards results in legal liabilities."),
  bulB("i) Data Segregation in Multi-Tenancy", "When serving multiple business units, poor data segregation may allow unauthorized cross-unit access."),
  bulB("j) Lack of Visibility & Monitoring", "Without adequate monitoring, detecting and responding to incidents becomes difficult, prolonging exposure."),
  h3("Securing Private Clouds:"),
  bulB("Right Platform", "Choose platforms like VMware, OpenStack, Red Hat, Azure Stack, or AWS Outposts with strong security capabilities."),
  bulB("Patch Management", "Regularly update OS (VM images), firmware, and hardware. Define update timelines and rollout procedures."),
  bulB("Staff Training", "Train IT teams on secure VM provisioning, PKI, identity management, and data protection."),
  bulB("Regular Audits", "Conduct independent third-party assessments (CSA STAR) and update security policies regularly."),
  h3("2. Public Cloud Security:"),
  p("Security in public cloud environments is primarily guided by the NIST Cybersecurity Framework. Since public clouds operate in a shared infrastructure model, security, identity management, and compliance are central concerns."),
  h3("Security Issues in Public Clouds:"),
  bulB("a) Multi-Tenancy Risks", "Multiple tenants share the same physical infrastructure. Hypervisor vulnerabilities or shared storage blocks may allow one tenant's VM to access another's data."),
  bulB("b) Lack of Visibility", "Cloud resources (VMs, containers, serverless, microservices) exist outside local IT control. Traditional monitoring tools are insufficient, creating blind spots in access tracking."),
  bulB("c) Misconfigurations", "Leaving ports open by default, using default passwords, or improper IAM settings are major causes of breaches. Gartner predicts 99% of cloud failures by 2025 will be due to human error."),
  bulB("d) Unmanaged Attack Surface", "Public-facing cloud services expose large attack surfaces. AWS S3 metadata can reveal storage block names and data center locations to attackers."),
  bulB("e) Zero-Day Exploits", "Vulnerabilities unknown to developers are exploited before patches are available. Cloud's interconnected nature increases exposure."),
  bulB("f) Advanced Persistent Threats (APTs)", "Long-term stealthy attacks where attackers infiltrate, stay hidden for months, and move laterally across workloads to exfiltrate data."),
  bulB("g) Insider Threats", "Former or current employees with authorized access may intentionally or accidentally cause breaches."),
  bulB("h) DDoS Attacks", "Public cloud services are prime targets for Distributed Denial of Service attacks that disrupt availability."),
  h3("Public Cloud Security Controls (CSP-Provided):"),
  bulB("Infrastructure Security", "VM key management, network security groups, firewall rules, encryption."),
  bulB("Network Security", "VPNs, DDoS protection, firewalls, network traffic monitoring."),
  bulB("Application Security", "WAFs, vulnerability scanning, runtime protection."),
  bulB("IAM", "MFA, identity federation, SSO, RBAC."),
  bulB("Compliance", "PCI DSS, HIPAA, GDPR compliance frameworks built into cloud services."),
  h3("3. Hybrid Cloud Security:"),
  p("Hybrid clouds combine on-premise IT infrastructure with public cloud services. The Cloud Security Alliance (CSA) Hybrid Cloud Security Working Group identifies four cross-cloud security capabilities:"),
  bulB("Perimeter Security", "Protects physical and logical boundaries between private and public cloud environments."),
  bulB("Transmission Security", "Secures migration of VMs, containers, and data across environments."),
  bulB("Storage Security", "Ensures secure data storage, backup, and restoration in hybrid setups."),
  bulB("Management Security", "Unified management of operations, permissions, identities, and authentication across clouds."),
  h3("Security Issues in Hybrid Clouds:"),
  bulB("a) DDoS Attacks", "Can disrupt both external communications with users and internal communications between cloud components."),
  bulB("b) Data Breaches", "Internet connectivity between endpoints increases risk of data leakage via misconfigurations, unauthorized access, and man-in-the-middle attacks."),
  bulB("c) Compliance Challenges", "Movement of data between private and public clouds complicates adherence to GDPR, HIPAA, PCI-DSS."),
  bulB("d) SLA Misalignment", "Each CSP defines its own APIs and SLAs; inconsistency across providers affects service quality."),
  bulB("e) Cloud Skills Gap", "Managing security across different platforms (AWS, Azure, GCP + on-premise) requires expertise that is often lacking."),
  bulB("f) Risk Assessment Fragmentation", "Each CSP and private cloud must be assessed individually, making holistic risk evaluation difficult."),
  h3("Securing Hybrid Clouds:"),
  bulB("Unified IAM Strategy", "MFA for privileged accounts, automated monitoring, least privilege access across all environments."),
  bulB("Automate Configuration", "Cloud Security Posture Management (CSPM) tools to enforce consistent configurations and prevent misconfigurations."),
  bulB("DevSecOps", "Integrate security into the development lifecycle to embed controls throughout the pipeline."),
  bulB("Data Security", "Encrypt data in transit and at rest; use hardware security modules (HSMs); enforce strict access policies."),
  bulB("Zero Trust Architecture", "No entity is automatically trusted; all access based on continuous authentication, contextual awareness, and adaptive security controls."),
  h3("Summary Comparison:"),
  sp(), tbl3("Aspect", "Private Cloud", "Public / Hybrid Cloud",
    [
      ["Control", "Full control (organization manages all)", "Shared with CSP (SRM applies)"],
      ["Physical Security", "Organization's responsibility; may be weak", "CSP provides enterprise-grade facilities"],
      ["Multi-tenancy Risk", "Low (single tenant)", "High (shared infra across customers)"],
      ["Insider Threats", "High (privileged admin access)", "Moderate (limited by CSP controls)"],
      ["Compliance", "Customizable; must self-certify", "CSP provides compliance frameworks"],
      ["Visibility", "Full internal visibility", "Limited; requires cloud-native monitoring tools"],
      ["Scalability & Resilience", "Limited by own hardware", "Global redundancy and geographic distribution"],
    ]
  ), sp(),
  hr(),

  // Footer
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 200 }, children: [new TextRun({ text: "— End of Unit IV Question Bank Answers —", italics: true, color: "888888", size: 20 })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Ramachandra College of Engineering, Eluru | Cloud Computing | B.Tech VI Sem", color: "888888", size: 18 })] }),
];

const doc = new Document({
  numbering: {
    config: [
      { reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      { reference: "numbers", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] }
    ]
  },
  styles: {
    default: { document: { run: { font: "Arial", size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 30, bold: true, font: "Arial", color: "1F3864" }, paragraph: { spacing: { before: 280, after: 140 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 26, bold: true, font: "Arial", color: "2E4A8A" }, paragraph: { spacing: { before: 200, after: 100 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 23, bold: true, font: "Arial", color: "1F5C8B" }, paragraph: { spacing: { before: 160, after: 80 }, outlineLevel: 2 } },
    ]
  },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1200, right: 1200, bottom: 1200, left: 1200 } } },
    children
  }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('/home/claude/CC_Unit4_Answers.docx', buf);
  console.log('Done!');
}).catch(e => { console.error(e); process.exit(1); });